// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vpicorv32_wrapper__Syms.h"


VL_ATTR_COLD void Vpicorv32_wrapper___024root__trace_init_sub__TOP__0(Vpicorv32_wrapper___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vpicorv32_wrapper__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32_wrapper___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+325,"clk", false,-1);
    tracep->declBit(c+326,"resetn", false,-1);
    tracep->declBit(c+327,"trap", false,-1);
    tracep->declBit(c+328,"trace_valid", false,-1);
    tracep->declQuad(c+329,"trace_data", false,-1, 35,0);
}

VL_ATTR_COLD void Vpicorv32_wrapper___024root__trace_init_sub__TOP__picorv32_wrapper__0(Vpicorv32_wrapper___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vpicorv32_wrapper__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32_wrapper___024root__trace_init_sub__TOP__picorv32_wrapper__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+337,"AXI_TEST", false,-1, 31,0);
    tracep->declBus(c+337,"VERBOSE", false,-1, 31,0);
    tracep->declBit(c+325,"clk", false,-1);
    tracep->declBit(c+326,"resetn", false,-1);
    tracep->declBit(c+122,"trap", false,-1);
    tracep->declBit(c+123,"trace_valid", false,-1);
    tracep->declQuad(c+124,"trace_data", false,-1, 35,0);
    tracep->declBit(c+112,"tests_passed", false,-1);
    tracep->declBus(c+126,"irq", false,-1, 31,0);
    tracep->declBus(c+41,"count_cycle", false,-1, 15,0);
    tracep->declBit(c+127,"mem_axi_awvalid", false,-1);
    tracep->declBit(c+316,"mem_axi_awready", false,-1);
    tracep->declBus(c+128,"mem_axi_awaddr", false,-1, 31,0);
    tracep->declBus(c+338,"mem_axi_awprot", false,-1, 2,0);
    tracep->declBit(c+129,"mem_axi_wvalid", false,-1);
    tracep->declBit(c+317,"mem_axi_wready", false,-1);
    tracep->declBus(c+130,"mem_axi_wdata", false,-1, 31,0);
    tracep->declBus(c+131,"mem_axi_wstrb", false,-1, 3,0);
    tracep->declBit(c+318,"mem_axi_bvalid", false,-1);
    tracep->declBit(c+132,"mem_axi_bready", false,-1);
    tracep->declBit(c+133,"mem_axi_arvalid", false,-1);
    tracep->declBit(c+319,"mem_axi_arready", false,-1);
    tracep->declBus(c+128,"mem_axi_araddr", false,-1, 31,0);
    tracep->declBus(c+134,"mem_axi_arprot", false,-1, 2,0);
    tracep->declBit(c+320,"mem_axi_rvalid", false,-1);
    tracep->declBit(c+135,"mem_axi_rready", false,-1);
    tracep->declBus(c+113,"mem_axi_rdata", false,-1, 31,0);
    tracep->declArray(c+1,"firmware_file", false,-1, 1023,0);
    tracep->declBus(c+42,"cycle_counter", false,-1, 31,0);
    tracep->pushNamePrefix("uut ");
    tracep->declBus(c+339,"ENABLE_COUNTERS", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_COUNTERS64", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_REGS_16_31", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_REGS_DUALPORT", false,-1, 0,0);
    tracep->declBus(c+339,"TWO_STAGE_SHIFT", false,-1, 0,0);
    tracep->declBus(c+340,"BARREL_SHIFTER", false,-1, 0,0);
    tracep->declBus(c+340,"TWO_CYCLE_COMPARE", false,-1, 0,0);
    tracep->declBus(c+340,"TWO_CYCLE_ALU", false,-1, 0,0);
    tracep->declBus(c+339,"COMPRESSED_ISA", false,-1, 0,0);
    tracep->declBus(c+339,"CATCH_MISALIGN", false,-1, 0,0);
    tracep->declBus(c+339,"CATCH_ILLINSN", false,-1, 0,0);
    tracep->declBus(c+340,"ENABLE_PCPI", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_MUL", false,-1, 0,0);
    tracep->declBus(c+340,"ENABLE_FAST_MUL", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_DIV", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_IRQ", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_IRQ_QREGS", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_IRQ_TIMER", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_TRACE", false,-1, 0,0);
    tracep->declBus(c+340,"REGS_INIT_ZERO", false,-1, 0,0);
    tracep->declBus(c+341,"MASKED_IRQ", false,-1, 31,0);
    tracep->declBus(c+342,"LATCHED_IRQ", false,-1, 31,0);
    tracep->declBus(c+341,"PROGADDR_RESET", false,-1, 31,0);
    tracep->declBus(c+343,"PROGADDR_IRQ", false,-1, 31,0);
    tracep->declBus(c+342,"STACKADDR", false,-1, 31,0);
    tracep->declBit(c+325,"clk", false,-1);
    tracep->declBit(c+326,"resetn", false,-1);
    tracep->declBit(c+122,"trap", false,-1);
    tracep->declBit(c+127,"mem_axi_awvalid", false,-1);
    tracep->declBit(c+316,"mem_axi_awready", false,-1);
    tracep->declBus(c+128,"mem_axi_awaddr", false,-1, 31,0);
    tracep->declBus(c+338,"mem_axi_awprot", false,-1, 2,0);
    tracep->declBit(c+129,"mem_axi_wvalid", false,-1);
    tracep->declBit(c+317,"mem_axi_wready", false,-1);
    tracep->declBus(c+130,"mem_axi_wdata", false,-1, 31,0);
    tracep->declBus(c+131,"mem_axi_wstrb", false,-1, 3,0);
    tracep->declBit(c+318,"mem_axi_bvalid", false,-1);
    tracep->declBit(c+132,"mem_axi_bready", false,-1);
    tracep->declBit(c+133,"mem_axi_arvalid", false,-1);
    tracep->declBit(c+319,"mem_axi_arready", false,-1);
    tracep->declBus(c+128,"mem_axi_araddr", false,-1, 31,0);
    tracep->declBus(c+134,"mem_axi_arprot", false,-1, 2,0);
    tracep->declBit(c+320,"mem_axi_rvalid", false,-1);
    tracep->declBit(c+135,"mem_axi_rready", false,-1);
    tracep->declBus(c+113,"mem_axi_rdata", false,-1, 31,0);
    tracep->declBit(c+136,"pcpi_valid", false,-1);
    tracep->declBus(c+137,"pcpi_insn", false,-1, 31,0);
    tracep->declBus(c+138,"pcpi_rs1", false,-1, 31,0);
    tracep->declBus(c+139,"pcpi_rs2", false,-1, 31,0);
    tracep->declBit(c+344,"pcpi_wr", false,-1);
    tracep->declBus(c+345,"pcpi_rd", false,-1, 31,0);
    tracep->declBit(c+346,"pcpi_wait", false,-1);
    tracep->declBit(c+347,"pcpi_ready", false,-1);
    tracep->declBus(c+126,"irq", false,-1, 31,0);
    tracep->declBus(c+140,"eoi", false,-1, 31,0);
    tracep->declBit(c+123,"trace_valid", false,-1);
    tracep->declQuad(c+124,"trace_data", false,-1, 35,0);
    tracep->declBit(c+43,"mem_valid", false,-1);
    tracep->declBus(c+128,"mem_addr", false,-1, 31,0);
    tracep->declBus(c+130,"mem_wdata", false,-1, 31,0);
    tracep->declBus(c+131,"mem_wstrb", false,-1, 3,0);
    tracep->declBit(c+141,"mem_instr", false,-1);
    tracep->declBit(c+321,"mem_ready", false,-1);
    tracep->declBus(c+113,"mem_rdata", false,-1, 31,0);
    tracep->pushNamePrefix("axi_adapter ");
    tracep->declBit(c+325,"clk", false,-1);
    tracep->declBit(c+326,"resetn", false,-1);
    tracep->declBit(c+127,"mem_axi_awvalid", false,-1);
    tracep->declBit(c+316,"mem_axi_awready", false,-1);
    tracep->declBus(c+128,"mem_axi_awaddr", false,-1, 31,0);
    tracep->declBus(c+338,"mem_axi_awprot", false,-1, 2,0);
    tracep->declBit(c+129,"mem_axi_wvalid", false,-1);
    tracep->declBit(c+317,"mem_axi_wready", false,-1);
    tracep->declBus(c+130,"mem_axi_wdata", false,-1, 31,0);
    tracep->declBus(c+131,"mem_axi_wstrb", false,-1, 3,0);
    tracep->declBit(c+318,"mem_axi_bvalid", false,-1);
    tracep->declBit(c+132,"mem_axi_bready", false,-1);
    tracep->declBit(c+133,"mem_axi_arvalid", false,-1);
    tracep->declBit(c+319,"mem_axi_arready", false,-1);
    tracep->declBus(c+128,"mem_axi_araddr", false,-1, 31,0);
    tracep->declBus(c+134,"mem_axi_arprot", false,-1, 2,0);
    tracep->declBit(c+320,"mem_axi_rvalid", false,-1);
    tracep->declBit(c+135,"mem_axi_rready", false,-1);
    tracep->declBus(c+113,"mem_axi_rdata", false,-1, 31,0);
    tracep->declBit(c+43,"mem_valid", false,-1);
    tracep->declBit(c+141,"mem_instr", false,-1);
    tracep->declBit(c+321,"mem_ready", false,-1);
    tracep->declBus(c+128,"mem_addr", false,-1, 31,0);
    tracep->declBus(c+130,"mem_wdata", false,-1, 31,0);
    tracep->declBus(c+131,"mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+113,"mem_rdata", false,-1, 31,0);
    tracep->declBit(c+44,"ack_awvalid", false,-1);
    tracep->declBit(c+45,"ack_arvalid", false,-1);
    tracep->declBit(c+46,"ack_wvalid", false,-1);
    tracep->declBit(c+47,"xfer_done", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("picorv32_core ");
    tracep->declBus(c+339,"ENABLE_COUNTERS", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_COUNTERS64", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_REGS_16_31", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_REGS_DUALPORT", false,-1, 0,0);
    tracep->declBus(c+340,"LATCHED_MEM_RDATA", false,-1, 0,0);
    tracep->declBus(c+339,"TWO_STAGE_SHIFT", false,-1, 0,0);
    tracep->declBus(c+340,"BARREL_SHIFTER", false,-1, 0,0);
    tracep->declBus(c+340,"TWO_CYCLE_COMPARE", false,-1, 0,0);
    tracep->declBus(c+340,"TWO_CYCLE_ALU", false,-1, 0,0);
    tracep->declBus(c+339,"COMPRESSED_ISA", false,-1, 0,0);
    tracep->declBus(c+339,"CATCH_MISALIGN", false,-1, 0,0);
    tracep->declBus(c+339,"CATCH_ILLINSN", false,-1, 0,0);
    tracep->declBus(c+340,"ENABLE_PCPI", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_MUL", false,-1, 0,0);
    tracep->declBus(c+340,"ENABLE_FAST_MUL", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_DIV", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_IRQ", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_IRQ_QREGS", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_IRQ_TIMER", false,-1, 0,0);
    tracep->declBus(c+339,"ENABLE_TRACE", false,-1, 0,0);
    tracep->declBus(c+340,"REGS_INIT_ZERO", false,-1, 0,0);
    tracep->declBus(c+341,"MASKED_IRQ", false,-1, 31,0);
    tracep->declBus(c+342,"LATCHED_IRQ", false,-1, 31,0);
    tracep->declBus(c+341,"PROGADDR_RESET", false,-1, 31,0);
    tracep->declBus(c+343,"PROGADDR_IRQ", false,-1, 31,0);
    tracep->declBus(c+342,"STACKADDR", false,-1, 31,0);
    tracep->declBit(c+325,"clk", false,-1);
    tracep->declBit(c+326,"resetn", false,-1);
    tracep->declBit(c+122,"trap", false,-1);
    tracep->declBit(c+43,"mem_valid", false,-1);
    tracep->declBit(c+141,"mem_instr", false,-1);
    tracep->declBit(c+321,"mem_ready", false,-1);
    tracep->declBus(c+128,"mem_addr", false,-1, 31,0);
    tracep->declBus(c+130,"mem_wdata", false,-1, 31,0);
    tracep->declBus(c+131,"mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+113,"mem_rdata", false,-1, 31,0);
    tracep->declBit(c+35,"mem_la_read", false,-1);
    tracep->declBit(c+331,"mem_la_write", false,-1);
    tracep->declBus(c+332,"mem_la_addr", false,-1, 31,0);
    tracep->declBus(c+142,"mem_la_wdata", false,-1, 31,0);
    tracep->declBus(c+143,"mem_la_wstrb", false,-1, 3,0);
    tracep->declBit(c+136,"pcpi_valid", false,-1);
    tracep->declBus(c+137,"pcpi_insn", false,-1, 31,0);
    tracep->declBus(c+138,"pcpi_rs1", false,-1, 31,0);
    tracep->declBus(c+139,"pcpi_rs2", false,-1, 31,0);
    tracep->declBit(c+344,"pcpi_wr", false,-1);
    tracep->declBus(c+345,"pcpi_rd", false,-1, 31,0);
    tracep->declBit(c+346,"pcpi_wait", false,-1);
    tracep->declBit(c+347,"pcpi_ready", false,-1);
    tracep->declBus(c+126,"irq", false,-1, 31,0);
    tracep->declBus(c+140,"eoi", false,-1, 31,0);
    tracep->declBit(c+123,"trace_valid", false,-1);
    tracep->declQuad(c+124,"trace_data", false,-1, 35,0);
    tracep->declBus(c+348,"irq_timer", false,-1, 31,0);
    tracep->declBus(c+349,"irq_ebreak", false,-1, 31,0);
    tracep->declBus(c+350,"irq_buserror", false,-1, 31,0);
    tracep->declBus(c+351,"irqregs_offset", false,-1, 31,0);
    tracep->declBus(c+352,"regfile_size", false,-1, 31,0);
    tracep->declBus(c+353,"regindex_bits", false,-1, 31,0);
    tracep->declBus(c+339,"WITH_PCPI", false,-1, 0,0);
    tracep->declQuad(c+354,"TRACE_BRANCH", false,-1, 35,0);
    tracep->declQuad(c+356,"TRACE_ADDR", false,-1, 35,0);
    tracep->declQuad(c+358,"TRACE_IRQ", false,-1, 35,0);
    tracep->declQuad(c+144,"count_cycle", false,-1, 63,0);
    tracep->declQuad(c+146,"count_instr", false,-1, 63,0);
    tracep->declBus(c+148,"reg_pc", false,-1, 31,0);
    tracep->declBus(c+149,"reg_next_pc", false,-1, 31,0);
    tracep->declBus(c+138,"reg_op1", false,-1, 31,0);
    tracep->declBus(c+139,"reg_op2", false,-1, 31,0);
    tracep->declBus(c+150,"reg_out", false,-1, 31,0);
    tracep->declBus(c+151,"reg_sh", false,-1, 4,0);
    tracep->declBus(c+48,"next_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+49,"dbg_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+50,"dbg_insn_addr", false,-1, 31,0);
    tracep->declBit(c+43,"dbg_mem_valid", false,-1);
    tracep->declBit(c+141,"dbg_mem_instr", false,-1);
    tracep->declBit(c+321,"dbg_mem_ready", false,-1);
    tracep->declBus(c+128,"dbg_mem_addr", false,-1, 31,0);
    tracep->declBus(c+130,"dbg_mem_wdata", false,-1, 31,0);
    tracep->declBus(c+131,"dbg_mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+113,"dbg_mem_rdata", false,-1, 31,0);
    tracep->declBus(c+152,"next_pc", false,-1, 31,0);
    tracep->declBit(c+153,"irq_delay", false,-1);
    tracep->declBit(c+154,"irq_active", false,-1);
    tracep->declBus(c+155,"irq_mask", false,-1, 31,0);
    tracep->declBus(c+156,"irq_pending", false,-1, 31,0);
    tracep->declBus(c+157,"timer", false,-1, 31,0);
    tracep->declBus(c+360,"i", false,-1, 31,0);
    tracep->declBit(c+51,"pcpi_mul_wr", false,-1);
    tracep->declBus(c+52,"pcpi_mul_rd", false,-1, 31,0);
    tracep->declBit(c+158,"pcpi_mul_wait", false,-1);
    tracep->declBit(c+53,"pcpi_mul_ready", false,-1);
    tracep->declBit(c+159,"pcpi_div_wr", false,-1);
    tracep->declBus(c+160,"pcpi_div_rd", false,-1, 31,0);
    tracep->declBit(c+161,"pcpi_div_wait", false,-1);
    tracep->declBit(c+162,"pcpi_div_ready", false,-1);
    tracep->declBit(c+163,"pcpi_int_wr", false,-1);
    tracep->declBus(c+164,"pcpi_int_rd", false,-1, 31,0);
    tracep->declBit(c+165,"pcpi_int_wait", false,-1);
    tracep->declBit(c+166,"pcpi_int_ready", false,-1);
    tracep->declBus(c+54,"mem_state", false,-1, 1,0);
    tracep->declBus(c+167,"mem_wordsize", false,-1, 1,0);
    tracep->declBus(c+333,"mem_rdata_word", false,-1, 31,0);
    tracep->declBus(c+168,"mem_rdata_q", false,-1, 31,0);
    tracep->declBit(c+169,"mem_do_prefetch", false,-1);
    tracep->declBit(c+170,"mem_do_rinst", false,-1);
    tracep->declBit(c+171,"mem_do_rdata", false,-1);
    tracep->declBit(c+172,"mem_do_wdata", false,-1);
    tracep->declBit(c+36,"mem_xfer", false,-1);
    tracep->declBit(c+55,"mem_la_secondword", false,-1);
    tracep->declBit(c+56,"mem_la_firstword_reg", false,-1);
    tracep->declBit(c+57,"last_mem_valid", false,-1);
    tracep->declBit(c+173,"mem_la_firstword", false,-1);
    tracep->declBit(c+37,"mem_la_firstword_xfer", false,-1);
    tracep->declBit(c+58,"prefetched_high_word", false,-1);
    tracep->declBit(c+334,"clear_prefetched_high_word", false,-1);
    tracep->declBus(c+59,"mem_16bit_buffer", false,-1, 15,0);
    tracep->declBus(c+38,"mem_rdata_latched_noshuffle", false,-1, 31,0);
    tracep->declBus(c+39,"mem_rdata_latched", false,-1, 31,0);
    tracep->declBit(c+335,"mem_la_use_prefetched_high_word", false,-1);
    tracep->declBit(c+174,"mem_busy", false,-1);
    tracep->declBit(c+40,"mem_done", false,-1);
    tracep->declBit(c+175,"instr_lui", false,-1);
    tracep->declBit(c+176,"instr_auipc", false,-1);
    tracep->declBit(c+177,"instr_jal", false,-1);
    tracep->declBit(c+178,"instr_jalr", false,-1);
    tracep->declBit(c+179,"instr_beq", false,-1);
    tracep->declBit(c+180,"instr_bne", false,-1);
    tracep->declBit(c+181,"instr_blt", false,-1);
    tracep->declBit(c+182,"instr_bge", false,-1);
    tracep->declBit(c+183,"instr_bltu", false,-1);
    tracep->declBit(c+184,"instr_bgeu", false,-1);
    tracep->declBit(c+185,"instr_lb", false,-1);
    tracep->declBit(c+186,"instr_lh", false,-1);
    tracep->declBit(c+187,"instr_lw", false,-1);
    tracep->declBit(c+188,"instr_lbu", false,-1);
    tracep->declBit(c+189,"instr_lhu", false,-1);
    tracep->declBit(c+190,"instr_sb", false,-1);
    tracep->declBit(c+191,"instr_sh", false,-1);
    tracep->declBit(c+192,"instr_sw", false,-1);
    tracep->declBit(c+193,"instr_addi", false,-1);
    tracep->declBit(c+194,"instr_slti", false,-1);
    tracep->declBit(c+195,"instr_sltiu", false,-1);
    tracep->declBit(c+196,"instr_xori", false,-1);
    tracep->declBit(c+197,"instr_ori", false,-1);
    tracep->declBit(c+198,"instr_andi", false,-1);
    tracep->declBit(c+199,"instr_slli", false,-1);
    tracep->declBit(c+200,"instr_srli", false,-1);
    tracep->declBit(c+201,"instr_srai", false,-1);
    tracep->declBit(c+202,"instr_add", false,-1);
    tracep->declBit(c+203,"instr_sub", false,-1);
    tracep->declBit(c+204,"instr_sll", false,-1);
    tracep->declBit(c+205,"instr_slt", false,-1);
    tracep->declBit(c+206,"instr_sltu", false,-1);
    tracep->declBit(c+207,"instr_xor", false,-1);
    tracep->declBit(c+208,"instr_srl", false,-1);
    tracep->declBit(c+209,"instr_sra", false,-1);
    tracep->declBit(c+210,"instr_or", false,-1);
    tracep->declBit(c+211,"instr_and", false,-1);
    tracep->declBit(c+212,"instr_rdcycle", false,-1);
    tracep->declBit(c+213,"instr_rdcycleh", false,-1);
    tracep->declBit(c+214,"instr_rdinstr", false,-1);
    tracep->declBit(c+215,"instr_rdinstrh", false,-1);
    tracep->declBit(c+216,"instr_ecall_ebreak", false,-1);
    tracep->declBit(c+217,"instr_getq", false,-1);
    tracep->declBit(c+218,"instr_setq", false,-1);
    tracep->declBit(c+219,"instr_retirq", false,-1);
    tracep->declBit(c+220,"instr_maskirq", false,-1);
    tracep->declBit(c+221,"instr_waitirq", false,-1);
    tracep->declBit(c+222,"instr_timer", false,-1);
    tracep->declBit(c+223,"instr_trap", false,-1);
    tracep->declBus(c+224,"decoded_rd", false,-1, 5,0);
    tracep->declBus(c+60,"decoded_rs1", false,-1, 5,0);
    tracep->declBus(c+225,"decoded_rs2", false,-1, 5,0);
    tracep->declBus(c+226,"decoded_imm", false,-1, 31,0);
    tracep->declBus(c+227,"decoded_imm_j", false,-1, 31,0);
    tracep->declBit(c+228,"decoder_trigger", false,-1);
    tracep->declBit(c+229,"decoder_trigger_q", false,-1);
    tracep->declBit(c+230,"decoder_pseudo_trigger", false,-1);
    tracep->declBit(c+61,"decoder_pseudo_trigger_q", false,-1);
    tracep->declBit(c+231,"compressed_instr", false,-1);
    tracep->declBit(c+232,"is_lui_auipc_jal", false,-1);
    tracep->declBit(c+233,"is_lb_lh_lw_lbu_lhu", false,-1);
    tracep->declBit(c+234,"is_slli_srli_srai", false,-1);
    tracep->declBit(c+235,"is_jalr_addi_slti_sltiu_xori_ori_andi", false,-1);
    tracep->declBit(c+236,"is_sb_sh_sw", false,-1);
    tracep->declBit(c+237,"is_sll_srl_sra", false,-1);
    tracep->declBit(c+238,"is_lui_auipc_jal_jalr_addi_add_sub", false,-1);
    tracep->declBit(c+239,"is_slti_blt_slt", false,-1);
    tracep->declBit(c+240,"is_sltiu_bltu_sltu", false,-1);
    tracep->declBit(c+241,"is_beq_bne_blt_bge_bltu_bgeu", false,-1);
    tracep->declBit(c+242,"is_lbu_lhu_lw", false,-1);
    tracep->declBit(c+243,"is_alu_reg_imm", false,-1);
    tracep->declBit(c+244,"is_alu_reg_reg", false,-1);
    tracep->declBit(c+245,"is_compare", false,-1);
    tracep->declBit(c+246,"is_rdcycle_rdcycleh_rdinstr_rdinstrh", false,-1);
    tracep->declQuad(c+247,"new_ascii_instr", false,-1, 63,0);
    tracep->declQuad(c+249,"dbg_ascii_instr", false,-1, 63,0);
    tracep->declBus(c+251,"dbg_insn_imm", false,-1, 31,0);
    tracep->declBus(c+62,"dbg_insn_rs1", false,-1, 4,0);
    tracep->declBus(c+252,"dbg_insn_rs2", false,-1, 4,0);
    tracep->declBus(c+253,"dbg_insn_rd", false,-1, 4,0);
    tracep->declBus(c+254,"dbg_rs1val", false,-1, 31,0);
    tracep->declBus(c+255,"dbg_rs2val", false,-1, 31,0);
    tracep->declBit(c+256,"dbg_rs1val_valid", false,-1);
    tracep->declBit(c+257,"dbg_rs2val_valid", false,-1);
    tracep->declQuad(c+63,"q_ascii_instr", false,-1, 63,0);
    tracep->declBus(c+65,"q_insn_imm", false,-1, 31,0);
    tracep->declBus(c+66,"q_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+67,"q_insn_rs1", false,-1, 4,0);
    tracep->declBus(c+68,"q_insn_rs2", false,-1, 4,0);
    tracep->declBus(c+69,"q_insn_rd", false,-1, 4,0);
    tracep->declBit(c+70,"dbg_next", false,-1);
    tracep->declBit(c+258,"launch_next_insn", false,-1);
    tracep->declBit(c+71,"dbg_valid_insn", false,-1);
    tracep->declQuad(c+72,"cached_ascii_instr", false,-1, 63,0);
    tracep->declBus(c+74,"cached_insn_imm", false,-1, 31,0);
    tracep->declBus(c+75,"cached_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+76,"cached_insn_rs1", false,-1, 4,0);
    tracep->declBus(c+77,"cached_insn_rs2", false,-1, 4,0);
    tracep->declBus(c+78,"cached_insn_rd", false,-1, 4,0);
    tracep->declBus(c+361,"cpu_state_trap", false,-1, 7,0);
    tracep->declBus(c+362,"cpu_state_fetch", false,-1, 7,0);
    tracep->declBus(c+363,"cpu_state_ld_rs1", false,-1, 7,0);
    tracep->declBus(c+364,"cpu_state_ld_rs2", false,-1, 7,0);
    tracep->declBus(c+365,"cpu_state_exec", false,-1, 7,0);
    tracep->declBus(c+366,"cpu_state_shift", false,-1, 7,0);
    tracep->declBus(c+367,"cpu_state_stmem", false,-1, 7,0);
    tracep->declBus(c+368,"cpu_state_ldmem", false,-1, 7,0);
    tracep->declBus(c+259,"cpu_state", false,-1, 7,0);
    tracep->declBus(c+260,"irq_state", false,-1, 1,0);
    tracep->declArray(c+261,"dbg_ascii_state", false,-1, 127,0);
    tracep->declBit(c+265,"set_mem_do_rinst", false,-1);
    tracep->declBit(c+266,"set_mem_do_rdata", false,-1);
    tracep->declBit(c+267,"set_mem_do_wdata", false,-1);
    tracep->declBit(c+268,"latched_store", false,-1);
    tracep->declBit(c+269,"latched_stalu", false,-1);
    tracep->declBit(c+270,"latched_branch", false,-1);
    tracep->declBit(c+271,"latched_compr", false,-1);
    tracep->declBit(c+272,"latched_trace", false,-1);
    tracep->declBit(c+273,"latched_is_lu", false,-1);
    tracep->declBit(c+274,"latched_is_lh", false,-1);
    tracep->declBit(c+275,"latched_is_lb", false,-1);
    tracep->declBus(c+276,"latched_rd", false,-1, 5,0);
    tracep->declBus(c+277,"current_pc", false,-1, 31,0);
    tracep->declBus(c+278,"pcpi_timeout_counter", false,-1, 3,0);
    tracep->declBit(c+279,"pcpi_timeout", false,-1);
    tracep->declBus(c+280,"next_irq_pending", false,-1, 31,0);
    tracep->declBit(c+281,"do_waitirq", false,-1);
    tracep->declBus(c+282,"alu_out", false,-1, 31,0);
    tracep->declBus(c+283,"alu_out_q", false,-1, 31,0);
    tracep->declBit(c+284,"alu_out_0", false,-1);
    tracep->declBit(c+79,"alu_out_0_q", false,-1);
    tracep->declBit(c+80,"alu_wait", false,-1);
    tracep->declBit(c+81,"alu_wait_2", false,-1);
    tracep->declBus(c+285,"alu_add_sub", false,-1, 31,0);
    tracep->declBus(c+286,"alu_shl", false,-1, 31,0);
    tracep->declBus(c+287,"alu_shr", false,-1, 31,0);
    tracep->declBit(c+288,"alu_eq", false,-1);
    tracep->declBit(c+289,"alu_ltu", false,-1);
    tracep->declBit(c+290,"alu_lts", false,-1);
    tracep->declBit(c+82,"clear_prefetched_high_word_q", false,-1);
    tracep->declBit(c+291,"cpuregs_write", false,-1);
    tracep->declBus(c+292,"cpuregs_wrdata", false,-1, 31,0);
    tracep->declBus(c+293,"cpuregs_rs1", false,-1, 31,0);
    tracep->declBus(c+294,"cpuregs_rs2", false,-1, 31,0);
    tracep->declBus(c+369,"decoded_rs", false,-1, 5,0);
    tracep->pushNamePrefix("genblk1 ");
    tracep->pushNamePrefix("pcpi_mul ");
    tracep->declBus(c+370,"STEPS_AT_ONCE", false,-1, 31,0);
    tracep->declBus(c+371,"CARRY_CHAIN", false,-1, 31,0);
    tracep->declBit(c+325,"clk", false,-1);
    tracep->declBit(c+326,"resetn", false,-1);
    tracep->declBit(c+136,"pcpi_valid", false,-1);
    tracep->declBus(c+137,"pcpi_insn", false,-1, 31,0);
    tracep->declBus(c+138,"pcpi_rs1", false,-1, 31,0);
    tracep->declBus(c+139,"pcpi_rs2", false,-1, 31,0);
    tracep->declBit(c+51,"pcpi_wr", false,-1);
    tracep->declBus(c+52,"pcpi_rd", false,-1, 31,0);
    tracep->declBit(c+158,"pcpi_wait", false,-1);
    tracep->declBit(c+53,"pcpi_ready", false,-1);
    tracep->declBit(c+295,"instr_mul", false,-1);
    tracep->declBit(c+83,"instr_mulh", false,-1);
    tracep->declBit(c+84,"instr_mulhsu", false,-1);
    tracep->declBit(c+85,"instr_mulhu", false,-1);
    tracep->declBit(c+296,"instr_any_mul", false,-1);
    tracep->declBit(c+297,"instr_any_mulh", false,-1);
    tracep->declBit(c+86,"instr_rs1_signed", false,-1);
    tracep->declBit(c+83,"instr_rs2_signed", false,-1);
    tracep->declBit(c+87,"pcpi_wait_q", false,-1);
    tracep->declBit(c+336,"mul_start", false,-1);
    tracep->declQuad(c+88,"rs1", false,-1, 63,0);
    tracep->declQuad(c+90,"rs2", false,-1, 63,0);
    tracep->declQuad(c+92,"rd", false,-1, 63,0);
    tracep->declQuad(c+94,"rdx", false,-1, 63,0);
    tracep->declQuad(c+96,"next_rs1", false,-1, 63,0);
    tracep->declQuad(c+98,"next_rs2", false,-1, 63,0);
    tracep->declQuad(c+100,"this_rs2", false,-1, 63,0);
    tracep->declQuad(c+102,"next_rd", false,-1, 63,0);
    tracep->declQuad(c+104,"next_rdx", false,-1, 63,0);
    tracep->declQuad(c+106,"next_rdt", false,-1, 63,0);
    tracep->declBus(c+108,"mul_counter", false,-1, 6,0);
    tracep->declBit(c+109,"mul_waiting", false,-1);
    tracep->declBit(c+110,"mul_finish", false,-1);
    tracep->declBus(c+349,"i", false,-1, 31,0);
    tracep->declBus(c+372,"j", false,-1, 31,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("genblk2 ");
    tracep->pushNamePrefix("pcpi_div ");
    tracep->declBit(c+325,"clk", false,-1);
    tracep->declBit(c+326,"resetn", false,-1);
    tracep->declBit(c+136,"pcpi_valid", false,-1);
    tracep->declBus(c+137,"pcpi_insn", false,-1, 31,0);
    tracep->declBus(c+138,"pcpi_rs1", false,-1, 31,0);
    tracep->declBus(c+139,"pcpi_rs2", false,-1, 31,0);
    tracep->declBit(c+159,"pcpi_wr", false,-1);
    tracep->declBus(c+160,"pcpi_rd", false,-1, 31,0);
    tracep->declBit(c+161,"pcpi_wait", false,-1);
    tracep->declBit(c+162,"pcpi_ready", false,-1);
    tracep->declBit(c+298,"instr_div", false,-1);
    tracep->declBit(c+299,"instr_divu", false,-1);
    tracep->declBit(c+300,"instr_rem", false,-1);
    tracep->declBit(c+301,"instr_remu", false,-1);
    tracep->declBit(c+302,"instr_any_div_rem", false,-1);
    tracep->declBit(c+111,"pcpi_wait_q", false,-1);
    tracep->declBit(c+303,"start", false,-1);
    tracep->declBus(c+304,"dividend", false,-1, 31,0);
    tracep->declQuad(c+305,"divisor", false,-1, 62,0);
    tracep->declBus(c+307,"quotient", false,-1, 31,0);
    tracep->declBus(c+308,"quotient_msk", false,-1, 31,0);
    tracep->declBit(c+309,"running", false,-1);
    tracep->declBit(c+310,"outsign", false,-1);
    tracep->popNamePrefix(4);
}

VL_ATTR_COLD void Vpicorv32_wrapper___024root__trace_init_sub__TOP__picorv32_wrapper__mem__0(Vpicorv32_wrapper___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vpicorv32_wrapper__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32_wrapper___024root__trace_init_sub__TOP__picorv32_wrapper__mem__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+337,"AXI_TEST", false,-1, 31,0);
    tracep->declBus(c+337,"VERBOSE", false,-1, 31,0);
    tracep->declBit(c+325,"clk", false,-1);
    tracep->declBit(c+127,"mem_axi_awvalid", false,-1);
    tracep->declBit(c+316,"mem_axi_awready", false,-1);
    tracep->declBus(c+128,"mem_axi_awaddr", false,-1, 31,0);
    tracep->declBus(c+338,"mem_axi_awprot", false,-1, 2,0);
    tracep->declBit(c+129,"mem_axi_wvalid", false,-1);
    tracep->declBit(c+317,"mem_axi_wready", false,-1);
    tracep->declBus(c+130,"mem_axi_wdata", false,-1, 31,0);
    tracep->declBus(c+131,"mem_axi_wstrb", false,-1, 3,0);
    tracep->declBit(c+318,"mem_axi_bvalid", false,-1);
    tracep->declBit(c+132,"mem_axi_bready", false,-1);
    tracep->declBit(c+133,"mem_axi_arvalid", false,-1);
    tracep->declBit(c+319,"mem_axi_arready", false,-1);
    tracep->declBus(c+128,"mem_axi_araddr", false,-1, 31,0);
    tracep->declBus(c+134,"mem_axi_arprot", false,-1, 2,0);
    tracep->declBit(c+320,"mem_axi_rvalid", false,-1);
    tracep->declBit(c+135,"mem_axi_rready", false,-1);
    tracep->declBus(c+113,"mem_axi_rdata", false,-1, 31,0);
    tracep->declBit(c+112,"tests_passed", false,-1);
    tracep->declBit(c+33,"verbose", false,-1);
    tracep->declBit(c+34,"axi_test", false,-1);
    tracep->declQuad(c+311,"xorshift64_state", false,-1, 63,0);
    tracep->declBus(c+313,"fast_axi_transaction", false,-1, 2,0);
    tracep->declBus(c+314,"async_axi_transaction", false,-1, 4,0);
    tracep->declBus(c+315,"delay_axi_transaction", false,-1, 4,0);
    tracep->declBit(c+114,"latched_raddr_en", false,-1);
    tracep->declBit(c+115,"latched_waddr_en", false,-1);
    tracep->declBit(c+116,"latched_wdata_en", false,-1);
    tracep->declBit(c+322,"fast_raddr", false,-1);
    tracep->declBit(c+323,"fast_waddr", false,-1);
    tracep->declBit(c+324,"fast_wdata", false,-1);
    tracep->declBus(c+117,"latched_raddr", false,-1, 31,0);
    tracep->declBus(c+118,"latched_waddr", false,-1, 31,0);
    tracep->declBus(c+119,"latched_wdata", false,-1, 31,0);
    tracep->declBus(c+120,"latched_wstrb", false,-1, 3,0);
    tracep->declBit(c+121,"latched_rinsn", false,-1);
}

VL_ATTR_COLD void Vpicorv32_wrapper___024root__trace_init_top(Vpicorv32_wrapper___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vpicorv32_wrapper__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32_wrapper___024root__trace_init_top\n"); );
    // Body
    Vpicorv32_wrapper___024root__trace_init_sub__TOP__0(vlSelf, tracep);
    tracep->pushNamePrefix("picorv32_wrapper ");
    Vpicorv32_wrapper___024root__trace_init_sub__TOP__picorv32_wrapper__0(vlSelf, tracep);
    tracep->pushNamePrefix("mem ");
    Vpicorv32_wrapper___024root__trace_init_sub__TOP__picorv32_wrapper__mem__0(vlSelf, tracep);
    tracep->popNamePrefix(2);
}

VL_ATTR_COLD void Vpicorv32_wrapper___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vpicorv32_wrapper___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vpicorv32_wrapper___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vpicorv32_wrapper___024root__trace_register(Vpicorv32_wrapper___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vpicorv32_wrapper__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32_wrapper___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vpicorv32_wrapper___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vpicorv32_wrapper___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vpicorv32_wrapper___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vpicorv32_wrapper___024root__trace_full_sub_0(Vpicorv32_wrapper___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vpicorv32_wrapper___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32_wrapper___024root__trace_full_top_0\n"); );
    // Init
    Vpicorv32_wrapper___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vpicorv32_wrapper___024root*>(voidSelf);
    Vpicorv32_wrapper__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vpicorv32_wrapper___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vpicorv32_wrapper___024root__trace_full_sub_0(Vpicorv32_wrapper___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vpicorv32_wrapper__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32_wrapper___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullWData(oldp+1,(vlSymsp->TOP__picorv32_wrapper.__PVT__firmware_file),1024);
    bufp->fullBit(oldp+33,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__verbose));
    bufp->fullBit(oldp+34,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__axi_test));
    bufp->fullBit(oldp+35,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_read));
    bufp->fullBit(oldp+36,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_xfer));
    bufp->fullBit(oldp+37,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_firstword_xfer));
    bufp->fullIData(oldp+38,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_rdata_latched_noshuffle),32);
    bufp->fullIData(oldp+39,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_rdata_latched),32);
    bufp->fullBit(oldp+40,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_done));
    bufp->fullSData(oldp+41,(vlSymsp->TOP__picorv32_wrapper.__PVT__count_cycle),16);
    bufp->fullIData(oldp+42,(vlSymsp->TOP__picorv32_wrapper.__PVT__cycle_counter),32);
    bufp->fullBit(oldp+43,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__mem_valid));
    bufp->fullBit(oldp+44,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__axi_adapter__DOT__ack_awvalid));
    bufp->fullBit(oldp+45,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__axi_adapter__DOT__ack_arvalid));
    bufp->fullBit(oldp+46,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__axi_adapter__DOT__ack_wvalid));
    bufp->fullBit(oldp+47,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__axi_adapter__DOT__xfer_done));
    bufp->fullIData(oldp+48,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__next_insn_opcode),32);
    bufp->fullIData(oldp+49,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_insn_opcode),32);
    bufp->fullIData(oldp+50,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_insn_addr),32);
    bufp->fullBit(oldp+51,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_mul_wr));
    bufp->fullIData(oldp+52,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_mul_rd),32);
    bufp->fullBit(oldp+53,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_mul_ready));
    bufp->fullCData(oldp+54,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_state),2);
    bufp->fullBit(oldp+55,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_secondword));
    bufp->fullBit(oldp+56,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_firstword_reg));
    bufp->fullBit(oldp+57,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__last_mem_valid));
    bufp->fullBit(oldp+58,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__prefetched_high_word));
    bufp->fullSData(oldp+59,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_16bit_buffer),16);
    bufp->fullCData(oldp+60,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__decoded_rs1),6);
    bufp->fullBit(oldp+61,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__decoder_pseudo_trigger_q));
    bufp->fullCData(oldp+62,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_insn_rs1),5);
    bufp->fullQData(oldp+63,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__q_ascii_instr),64);
    bufp->fullIData(oldp+65,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__q_insn_imm),32);
    bufp->fullIData(oldp+66,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__q_insn_opcode),32);
    bufp->fullCData(oldp+67,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__q_insn_rs1),5);
    bufp->fullCData(oldp+68,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__q_insn_rs2),5);
    bufp->fullCData(oldp+69,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__q_insn_rd),5);
    bufp->fullBit(oldp+70,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_next));
    bufp->fullBit(oldp+71,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_valid_insn));
    bufp->fullQData(oldp+72,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cached_ascii_instr),64);
    bufp->fullIData(oldp+74,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cached_insn_imm),32);
    bufp->fullIData(oldp+75,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cached_insn_opcode),32);
    bufp->fullCData(oldp+76,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cached_insn_rs1),5);
    bufp->fullCData(oldp+77,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cached_insn_rs2),5);
    bufp->fullCData(oldp+78,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cached_insn_rd),5);
    bufp->fullBit(oldp+79,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__alu_out_0_q));
    bufp->fullBit(oldp+80,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__alu_wait));
    bufp->fullBit(oldp+81,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__alu_wait_2));
    bufp->fullBit(oldp+82,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__clear_prefetched_high_word_q));
    bufp->fullBit(oldp+83,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulh));
    bufp->fullBit(oldp+84,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulhsu));
    bufp->fullBit(oldp+85,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulhu));
    bufp->fullBit(oldp+86,(((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulh) 
                            | (IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulhsu))));
    bufp->fullBit(oldp+87,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_wait_q));
    bufp->fullQData(oldp+88,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__rs1),64);
    bufp->fullQData(oldp+90,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__rs2),64);
    bufp->fullQData(oldp+92,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__rd),64);
    bufp->fullQData(oldp+94,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__rdx),64);
    bufp->fullQData(oldp+96,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__next_rs1),64);
    bufp->fullQData(oldp+98,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__next_rs2),64);
    bufp->fullQData(oldp+100,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__this_rs2),64);
    bufp->fullQData(oldp+102,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__next_rd),64);
    bufp->fullQData(oldp+104,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__next_rdx),64);
    bufp->fullQData(oldp+106,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__next_rdt),64);
    bufp->fullCData(oldp+108,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__mul_counter),7);
    bufp->fullBit(oldp+109,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__mul_waiting));
    bufp->fullBit(oldp+110,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__mul_finish));
    bufp->fullBit(oldp+111,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_wait_q));
    bufp->fullBit(oldp+112,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__tests_passed));
    bufp->fullIData(oldp+113,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__mem_axi_rdata),32);
    bufp->fullBit(oldp+114,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__latched_raddr_en));
    bufp->fullBit(oldp+115,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__latched_waddr_en));
    bufp->fullBit(oldp+116,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__latched_wdata_en));
    bufp->fullIData(oldp+117,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__latched_raddr),32);
    bufp->fullIData(oldp+118,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__latched_waddr),32);
    bufp->fullIData(oldp+119,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__latched_wdata),32);
    bufp->fullCData(oldp+120,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__latched_wstrb),4);
    bufp->fullBit(oldp+121,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__latched_rinsn));
    bufp->fullBit(oldp+122,(vlSymsp->TOP__picorv32_wrapper.trap));
    bufp->fullBit(oldp+123,(vlSymsp->TOP__picorv32_wrapper.trace_valid));
    bufp->fullQData(oldp+124,(vlSymsp->TOP__picorv32_wrapper.trace_data),36);
    bufp->fullIData(oldp+126,(vlSymsp->TOP__picorv32_wrapper.__PVT__irq),32);
    bufp->fullBit(oldp+127,(vlSymsp->TOP__picorv32_wrapper.__PVT__mem_axi_awvalid));
    bufp->fullIData(oldp+128,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__mem_addr),32);
    bufp->fullBit(oldp+129,(vlSymsp->TOP__picorv32_wrapper.__PVT__mem_axi_wvalid));
    bufp->fullIData(oldp+130,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__mem_wdata),32);
    bufp->fullCData(oldp+131,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__mem_wstrb),4);
    bufp->fullBit(oldp+132,(vlSymsp->TOP__picorv32_wrapper.__PVT__mem_axi_bready));
    bufp->fullBit(oldp+133,(vlSymsp->TOP__picorv32_wrapper.__PVT__mem_axi_arvalid));
    bufp->fullCData(oldp+134,(((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__mem_instr)
                                ? 4U : 0U)),3);
    bufp->fullBit(oldp+135,(vlSymsp->TOP__picorv32_wrapper.__PVT__mem_axi_rready));
    bufp->fullBit(oldp+136,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__pcpi_valid));
    bufp->fullIData(oldp+137,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__pcpi_insn),32);
    bufp->fullIData(oldp+138,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op1),32);
    bufp->fullIData(oldp+139,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op2),32);
    bufp->fullIData(oldp+140,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__eoi),32);
    bufp->fullBit(oldp+141,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__mem_instr));
    bufp->fullIData(oldp+142,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_wdata),32);
    bufp->fullCData(oldp+143,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_wstrb),4);
    bufp->fullQData(oldp+144,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__count_cycle),64);
    bufp->fullQData(oldp+146,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__count_instr),64);
    bufp->fullIData(oldp+148,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_pc),32);
    bufp->fullIData(oldp+149,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_next_pc),32);
    bufp->fullIData(oldp+150,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_out),32);
    bufp->fullCData(oldp+151,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_sh),5);
    bufp->fullIData(oldp+152,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__next_pc),32);
    bufp->fullBit(oldp+153,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__irq_delay));
    bufp->fullBit(oldp+154,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__irq_active));
    bufp->fullIData(oldp+155,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__irq_mask),32);
    bufp->fullIData(oldp+156,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__irq_pending),32);
    bufp->fullIData(oldp+157,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__timer),32);
    bufp->fullBit(oldp+158,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_mul_wait));
    bufp->fullBit(oldp+159,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_div_wr));
    bufp->fullIData(oldp+160,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_div_rd),32);
    bufp->fullBit(oldp+161,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_div_wait));
    bufp->fullBit(oldp+162,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_div_ready));
    bufp->fullBit(oldp+163,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_int_wr));
    bufp->fullIData(oldp+164,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_int_rd),32);
    bufp->fullBit(oldp+165,(((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_mul_wait) 
                             | (IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_div_wait))));
    bufp->fullBit(oldp+166,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_int_ready));
    bufp->fullCData(oldp+167,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_wordsize),2);
    bufp->fullIData(oldp+168,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_rdata_q),32);
    bufp->fullBit(oldp+169,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_do_prefetch));
    bufp->fullBit(oldp+170,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_do_rinst));
    bufp->fullBit(oldp+171,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_do_rdata));
    bufp->fullBit(oldp+172,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_do_wdata));
    bufp->fullBit(oldp+173,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_firstword));
    bufp->fullBit(oldp+174,(((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_do_prefetch) 
                             | ((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_do_rinst) 
                                | ((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_do_rdata) 
                                   | (IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_do_wdata))))));
    bufp->fullBit(oldp+175,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_lui));
    bufp->fullBit(oldp+176,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_auipc));
    bufp->fullBit(oldp+177,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_jal));
    bufp->fullBit(oldp+178,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_jalr));
    bufp->fullBit(oldp+179,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_beq));
    bufp->fullBit(oldp+180,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_bne));
    bufp->fullBit(oldp+181,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_blt));
    bufp->fullBit(oldp+182,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_bge));
    bufp->fullBit(oldp+183,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_bltu));
    bufp->fullBit(oldp+184,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_bgeu));
    bufp->fullBit(oldp+185,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_lb));
    bufp->fullBit(oldp+186,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_lh));
    bufp->fullBit(oldp+187,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_lw));
    bufp->fullBit(oldp+188,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_lbu));
    bufp->fullBit(oldp+189,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_lhu));
    bufp->fullBit(oldp+190,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sb));
    bufp->fullBit(oldp+191,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sh));
    bufp->fullBit(oldp+192,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sw));
    bufp->fullBit(oldp+193,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_addi));
    bufp->fullBit(oldp+194,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_slti));
    bufp->fullBit(oldp+195,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sltiu));
    bufp->fullBit(oldp+196,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_xori));
    bufp->fullBit(oldp+197,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_ori));
    bufp->fullBit(oldp+198,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_andi));
    bufp->fullBit(oldp+199,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_slli));
    bufp->fullBit(oldp+200,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_srli));
    bufp->fullBit(oldp+201,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_srai));
    bufp->fullBit(oldp+202,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_add));
    bufp->fullBit(oldp+203,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sub));
    bufp->fullBit(oldp+204,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sll));
    bufp->fullBit(oldp+205,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_slt));
    bufp->fullBit(oldp+206,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sltu));
    bufp->fullBit(oldp+207,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_xor));
    bufp->fullBit(oldp+208,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_srl));
    bufp->fullBit(oldp+209,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sra));
    bufp->fullBit(oldp+210,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_or));
    bufp->fullBit(oldp+211,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_and));
    bufp->fullBit(oldp+212,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_rdcycle));
    bufp->fullBit(oldp+213,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_rdcycleh));
    bufp->fullBit(oldp+214,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_rdinstr));
    bufp->fullBit(oldp+215,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_rdinstrh));
    bufp->fullBit(oldp+216,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_ecall_ebreak));
    bufp->fullBit(oldp+217,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_getq));
    bufp->fullBit(oldp+218,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_setq));
    bufp->fullBit(oldp+219,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_retirq));
    bufp->fullBit(oldp+220,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_maskirq));
    bufp->fullBit(oldp+221,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_waitirq));
    bufp->fullBit(oldp+222,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_timer));
    bufp->fullBit(oldp+223,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_trap));
    bufp->fullCData(oldp+224,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__decoded_rd),6);
    bufp->fullCData(oldp+225,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__decoded_rs2),6);
    bufp->fullIData(oldp+226,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__decoded_imm),32);
    bufp->fullIData(oldp+227,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__decoded_imm_j),32);
    bufp->fullBit(oldp+228,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__decoder_trigger));
    bufp->fullBit(oldp+229,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__decoder_trigger_q));
    bufp->fullBit(oldp+230,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__decoder_pseudo_trigger));
    bufp->fullBit(oldp+231,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__compressed_instr));
    bufp->fullBit(oldp+232,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_lui_auipc_jal));
    bufp->fullBit(oldp+233,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_lb_lh_lw_lbu_lhu));
    bufp->fullBit(oldp+234,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_slli_srli_srai));
    bufp->fullBit(oldp+235,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi));
    bufp->fullBit(oldp+236,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_sb_sh_sw));
    bufp->fullBit(oldp+237,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_sll_srl_sra));
    bufp->fullBit(oldp+238,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_lui_auipc_jal_jalr_addi_add_sub));
    bufp->fullBit(oldp+239,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_slti_blt_slt));
    bufp->fullBit(oldp+240,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_sltiu_bltu_sltu));
    bufp->fullBit(oldp+241,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_beq_bne_blt_bge_bltu_bgeu));
    bufp->fullBit(oldp+242,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_lbu_lhu_lw));
    bufp->fullBit(oldp+243,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_alu_reg_imm));
    bufp->fullBit(oldp+244,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_alu_reg_reg));
    bufp->fullBit(oldp+245,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_compare));
    bufp->fullBit(oldp+246,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh));
    bufp->fullQData(oldp+247,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__new_ascii_instr),64);
    bufp->fullQData(oldp+249,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_ascii_instr),64);
    bufp->fullIData(oldp+251,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_insn_imm),32);
    bufp->fullCData(oldp+252,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_insn_rs2),5);
    bufp->fullCData(oldp+253,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_insn_rd),5);
    bufp->fullIData(oldp+254,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_rs1val),32);
    bufp->fullIData(oldp+255,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_rs2val),32);
    bufp->fullBit(oldp+256,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_rs1val_valid));
    bufp->fullBit(oldp+257,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_rs2val_valid));
    bufp->fullBit(oldp+258,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__launch_next_insn));
    bufp->fullCData(oldp+259,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cpu_state),8);
    bufp->fullCData(oldp+260,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__irq_state),2);
    bufp->fullWData(oldp+261,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_ascii_state),128);
    bufp->fullBit(oldp+265,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__set_mem_do_rinst));
    bufp->fullBit(oldp+266,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__set_mem_do_rdata));
    bufp->fullBit(oldp+267,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__set_mem_do_wdata));
    bufp->fullBit(oldp+268,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__latched_store));
    bufp->fullBit(oldp+269,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__latched_stalu));
    bufp->fullBit(oldp+270,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__latched_branch));
    bufp->fullBit(oldp+271,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__latched_compr));
    bufp->fullBit(oldp+272,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__latched_trace));
    bufp->fullBit(oldp+273,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__latched_is_lu));
    bufp->fullBit(oldp+274,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__latched_is_lh));
    bufp->fullBit(oldp+275,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__latched_is_lb));
    bufp->fullCData(oldp+276,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__latched_rd),6);
    bufp->fullIData(oldp+277,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__current_pc),32);
    bufp->fullCData(oldp+278,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_timeout_counter),4);
    bufp->fullBit(oldp+279,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_timeout));
    bufp->fullIData(oldp+280,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__next_irq_pending),32);
    bufp->fullBit(oldp+281,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__do_waitirq));
    bufp->fullIData(oldp+282,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__alu_out),32);
    bufp->fullIData(oldp+283,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__alu_out_q),32);
    bufp->fullBit(oldp+284,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__alu_out_0));
    bufp->fullIData(oldp+285,(((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sub)
                                ? (vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op1 
                                   - vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op2)
                                : (vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op1 
                                   + vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op2))),32);
    bufp->fullIData(oldp+286,((vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op1 
                               << (0x1fU & vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op2))),32);
    bufp->fullIData(oldp+287,((IData)((0x1ffffffffULL 
                                       & VL_SHIFTRS_QQI(33,33,5, 
                                                        (((QData)((IData)(
                                                                          (((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_sra) 
                                                                            | (IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__instr_srai)) 
                                                                           & (vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op1 
                                                                              >> 0x1fU)))) 
                                                          << 0x20U) 
                                                         | (QData)((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op1))), 
                                                        (0x1fU 
                                                         & vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op2))))),32);
    bufp->fullBit(oldp+288,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__alu_eq));
    bufp->fullBit(oldp+289,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__alu_ltu));
    bufp->fullBit(oldp+290,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__alu_lts));
    bufp->fullBit(oldp+291,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cpuregs_write));
    bufp->fullIData(oldp+292,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cpuregs_wrdata),32);
    bufp->fullIData(oldp+293,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cpuregs_rs1),32);
    bufp->fullIData(oldp+294,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__cpuregs_rs2),32);
    bufp->fullBit(oldp+295,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mul));
    bufp->fullBit(oldp+296,(((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mul) 
                             | (IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_any_mulh))));
    bufp->fullBit(oldp+297,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_any_mulh));
    bufp->fullBit(oldp+298,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_div));
    bufp->fullBit(oldp+299,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_divu));
    bufp->fullBit(oldp+300,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_rem));
    bufp->fullBit(oldp+301,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_remu));
    bufp->fullBit(oldp+302,(((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_div) 
                             | ((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_divu) 
                                | ((IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_rem) 
                                   | (IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_remu))))));
    bufp->fullBit(oldp+303,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__start));
    bufp->fullIData(oldp+304,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__dividend),32);
    bufp->fullQData(oldp+305,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__divisor),63);
    bufp->fullIData(oldp+307,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__quotient),32);
    bufp->fullIData(oldp+308,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__quotient_msk),32);
    bufp->fullBit(oldp+309,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__running));
    bufp->fullBit(oldp+310,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__outsign));
    bufp->fullQData(oldp+311,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__xorshift64_state),64);
    bufp->fullCData(oldp+313,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__fast_axi_transaction),3);
    bufp->fullCData(oldp+314,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__async_axi_transaction),5);
    bufp->fullCData(oldp+315,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__delay_axi_transaction),5);
    bufp->fullBit(oldp+316,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__mem_axi_awready));
    bufp->fullBit(oldp+317,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__mem_axi_wready));
    bufp->fullBit(oldp+318,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__mem_axi_bvalid));
    bufp->fullBit(oldp+319,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__mem_axi_arready));
    bufp->fullBit(oldp+320,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__mem_axi_rvalid));
    bufp->fullBit(oldp+321,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__dbg_mem_ready));
    bufp->fullBit(oldp+322,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__fast_raddr));
    bufp->fullBit(oldp+323,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__fast_waddr));
    bufp->fullBit(oldp+324,(vlSymsp->TOP__picorv32_wrapper__mem.__PVT__fast_wdata));
    bufp->fullBit(oldp+325,(vlSelf->clk));
    bufp->fullBit(oldp+326,(vlSelf->resetn));
    bufp->fullBit(oldp+327,(vlSelf->trap));
    bufp->fullBit(oldp+328,(vlSelf->trace_valid));
    bufp->fullQData(oldp+329,(vlSelf->trace_data),36);
    bufp->fullBit(oldp+331,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_write));
    bufp->fullIData(oldp+332,(((IData)(vlSymsp->TOP__picorv32_wrapper.uut__DOT__picorv32_core__DOT____VdfgTmp_hed8d3454__0)
                                ? (((vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__next_pc 
                                     >> 2U) + (IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_firstword_xfer)) 
                                   << 2U) : (0xfffffffcU 
                                             & vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__reg_op1))),32);
    bufp->fullIData(oldp+333,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_rdata_word),32);
    bufp->fullBit(oldp+334,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__clear_prefetched_high_word));
    bufp->fullBit(oldp+335,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__mem_la_use_prefetched_high_word));
    bufp->fullBit(oldp+336,(((~ (IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_wait_q)) 
                             & (IData)(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__pcpi_mul_wait))));
    bufp->fullIData(oldp+337,(0U),32);
    bufp->fullCData(oldp+338,(0U),3);
    bufp->fullBit(oldp+339,(1U));
    bufp->fullBit(oldp+340,(0U));
    bufp->fullIData(oldp+341,(0U),32);
    bufp->fullIData(oldp+342,(0xffffffffU),32);
    bufp->fullIData(oldp+343,(0x10U),32);
    bufp->fullBit(oldp+344,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__pcpi_wr));
    bufp->fullIData(oldp+345,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__pcpi_rd),32);
    bufp->fullBit(oldp+346,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__pcpi_wait));
    bufp->fullBit(oldp+347,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__pcpi_ready));
    bufp->fullIData(oldp+348,(0U),32);
    bufp->fullIData(oldp+349,(1U),32);
    bufp->fullIData(oldp+350,(2U),32);
    bufp->fullIData(oldp+351,(0x20U),32);
    bufp->fullIData(oldp+352,(0x24U),32);
    bufp->fullIData(oldp+353,(6U),32);
    bufp->fullQData(oldp+354,(0x100000000ULL),36);
    bufp->fullQData(oldp+356,(0x200000000ULL),36);
    bufp->fullQData(oldp+358,(0x800000000ULL),36);
    bufp->fullIData(oldp+360,(vlSymsp->TOP__picorv32_wrapper.__PVT__uut__DOT__picorv32_core__DOT__i),32);
    bufp->fullCData(oldp+361,(0x80U),8);
    bufp->fullCData(oldp+362,(0x40U),8);
    bufp->fullCData(oldp+363,(0x20U),8);
    bufp->fullCData(oldp+364,(0x10U),8);
    bufp->fullCData(oldp+365,(8U),8);
    bufp->fullCData(oldp+366,(4U),8);
    bufp->fullCData(oldp+367,(2U),8);
    bufp->fullCData(oldp+368,(1U),8);
    bufp->fullCData(oldp+369,(0U),6);
    bufp->fullIData(oldp+370,(1U),32);
    bufp->fullIData(oldp+371,(4U),32);
    bufp->fullIData(oldp+372,(0x40U),32);
}
